repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-annotations
          - flake8-quotes
          - flake8-picky-parentheses
          - flake8-docstrings
        args:
          - --docstring-convention=google
          - --config=.flake8

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort